# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_account_is_top_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_top_organization',
            field=models.NullBooleanField(default=False),
        ),
    ]
