# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-09 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendormanifest',
            name='baa_agreement_for_phi',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendormanifest',
            name='is_phi_approved',
            field=models.NullBooleanField(default=False),
        ),
    ]
