# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-30 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auto_20170109_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendormanifest',
            name='can_supplier_manage_freelancers',
            field=models.NullBooleanField(default=False, verbose_name=b'Supplier Manages Freelancers'),
        ),
    ]
