# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-07 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_vendormanifest_can_supplier_manages_freelancers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendormanifest',
            name='baa_agreement_for_phi',
        ),
        migrations.AddField(
            model_name='vendormanifest',
            name='baa_agreement_for_phi_signed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendormanifest',
            name='is_phi_approved',
            field=models.NullBooleanField(default=False, verbose_name=b'Is PHI approved'),
        ),
    ]
