# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_baa_agreement_for_phi_signed_datefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendormanifest',
            name='baa_agreement_for_phi_signed',
            field=models.DateField(blank=True, null=True, verbose_name=b'BAA Agreement for PHI Signed'),
        ),
    ]
