# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 08:54
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('accounts', '0005_auto_20161013_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GroupOwnerPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ViaGroup',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AddField(
            model_name='circususer',
            name='is_client_organization_administrator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupownerpermissions',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_group_permission', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='groupownerpermissions',
            name='permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_owner_permission', to='auth.Permission'),
        ),
        migrations.AddField(
            model_name='groupownerpermissions',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_permission_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupowner',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_group', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='groupowner',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='groupownerpermissions',
            unique_together=set([('group', 'permission', 'user')]),
        ),
    ]
