# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_account_is_top_organization'),
        ('accounts', '0008_add_create_client_organization_administrator_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupownerpermissions',
            name='parent_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_account', to='people.Account'),
        ),
    ]
