# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_set_permissions_to_OA_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circususer',
            name='is_client_organization_administrator',
            field=models.NullBooleanField(default=False),
        ),
    ]
