# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-08 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20170707_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circususer',
            name='user_type',
            field=models.CharField(choices=[(b'client', 'Client'), (b'via', 'VIA Staff'), (b'vendor', 'Vendor')], db_index=True, max_length=6),
        ),
    ]
