# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='notification_type',
            field=models.CharField(blank=True, default=b'message', max_length=50, verbose_name='users type'),
        ),
    ]
