# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 16:09
from __future__ import unicode_literals
from django.db import migrations
from django.core.management import call_command

fixture = 'fixtures\dvx_subject_code.json'

def load_fixture(apps, schema_editor):
    call_command('loaddata', fixture, app_label='dvx_subject_code')

def unload_fixture(apps, schema_editor):
    "Brutally deleting all entries for this model..."
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
