# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_load_intial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmanifest',
            name='expansion_rate_floor_override',
            field=models.NullBooleanField(default=False),
        ),
    ]
