# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientmanifest_expansion_rate_floor_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmanifest',
            name='auto_start_workflow',
            field=models.BooleanField(default=False),
        ),
    ]
