# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-13 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20160726_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmanifest',
            name='standard_translation_words_per_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
