# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-03 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_clientdiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdiscount',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=15, null=True),
        ),
    ]
