# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 09:10
from __future__ import unicode_literals

from django.db import migrations

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # Renaming groups 'Client Administrators' and 'Client Users' to 'Department Administrators' and 'Department Users'
    current_user_groups = apps.get_model("auth", "group").objects.filter(name__in=['Client Administrators', 'Client Users'])
    for group in current_user_groups:
        if group.name == 'Client Administrators':
            group.name = 'Department Administrators'
        else:
            group.name = 'Department Users'
        group.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20170203_1745'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
