# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-21 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_assign_groups_permissions_to_existing_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmanifest',
            name='default_client_user_level',
            field=models.ManyToManyField(blank=True, null=True,
                                         related_name='_clientmanifest_default_client_user_level_+', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='clientmanifest',
            name='enforce_customer_hierarchy',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientmanifest',
            name='baa_agreement_for_phi',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientmanifest',
            name='secure_jobs',
            field=models.BooleanField(default=False, verbose_name=b'Restricted Jobs'),
        ),
        migrations.AlterField(
            model_name='clientteamrole',
            name='role',
            field=models.CharField(blank=True, choices=[(b'pm', b'Project Manager'), (b'ae', b'Account Executive'), (b'tsg_eng', b'TSG Engineer'), (b'vle_eng', b'VLE Engineer'), (b'qa_eng', b'QA Engineer'), (b'sjt_member', b'Secure Job Team Member')], max_length=10, null=True),
        ),
    ]
