# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 05:29
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    #getting all clientmanifest
    client_manifests = apps.get_model("clients", "clientmanifest").objects.all()
    for cm in client_manifests:
        assigned_groups = []
        get_client_users = apps.get_model("accounts", "circususer").objects.filter(account_id=cm.client_id)
        for user in get_client_users:
            for g in user.groups.all():
                assigned_groups.append(g.id)
        assigned_groups = set(assigned_groups)
        for group in assigned_groups:
            cm.default_client_user_level.add(group)


def reverse_func(apps, schema_editor):
    # forwards_func() creates clientmanifest and groups m2m relation data,
    # so reverse_func() should delete them.
    client_manifests = apps.get_model("clients", "clientmanifest").objects.all()
    for cm in client_manifests:
        assigned_groups = []
        get_client_users = apps.get_model("accounts", "circususer").objects.filter(account_id=cm.client_id)
        for user in get_client_users:
            for g in user.groups.all():
                assigned_groups.append(g.id)
        assigned_groups = set(assigned_groups)
        for group in assigned_groups:
            cm.default_client_user_level.remove(group)


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_auto_20161221_1932'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
