# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-06 09:46
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    # Fetching all existing default groups created by Via Admin.
    current_user_groups = apps.get_model("auth", "group").objects.all()
    for group in current_user_groups:
        group_owner, created = apps.get_model("accounts", "groupowner").objects.get_or_create(
            group_id=group.id,
        )


def reverse_func(apps, schema_editor):
    # forwards_func() populates all existing default groups created by Via Admin. so reverse_func() should delete all the default groups.
    current_user_groups = apps.get_model("auth", "group").objects.all()
    # Getting only default groups created by VIA admin, not the user specific groups created by Client Users
    default_groups = []
    for group in current_user_groups:
        default_groups.append(apps.get_model("accounts", "groupowner").objects.filter(group_id=group.id, user_id=None))

    grp_ids = [g.group_id for grp in default_groups for g in grp]

    for grp_id in grp_ids:
        apps.get_model("accounts", "groupowner").objects.filter(group_id=grp_id, user_id=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_populate_clientmanifest_group_m2m_table'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
