# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_populating_groupowner_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmanifest',
            name='baa_agreement_for_phi',
            field=models.NullBooleanField(default=False, verbose_name='BAA Agreement in place for PHI'),
        ),
        migrations.AlterField(
            model_name='clientmanifest',
            name='default_client_user_level',
            field=models.ManyToManyField(blank=True, related_name='_clientmanifest_default_client_user_level_+', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='clientteamrole',
            name='role',
            field=models.CharField(blank=True, choices=[(b'pm', b'Project Manager'), (b'ae', b'Account Executive'), (b'tsg_eng', b'TSG Engineer'), (b'vle_eng', b'VLE Engineer'), (b'qa_eng', b'QA Engineer'), (b'sjt_member', b'Secure Job Team Member'), (b'psj_team', b'PHI Secure Job Team Member')], max_length=10, null=True),
        ),
    ]
