# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientManager',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('department', models.CharField(max_length=255, null=True, blank=True)),
                ('user_type', models.CharField(max_length=255, null=True, blank=True)),
                ('first_name', models.CharField(max_length=1000, null=True, blank=True)),
                ('last_name', models.CharField(max_length=1000, null=True, blank=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('reports_to_id', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ClientReport',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(unique=True, max_length=40)),
                ('description', models.CharField(max_length=40)),
                ('report_name', models.CharField(max_length=200, null=True, blank=True)),
                ('report_url_reverse', models.CharField(max_length=500, null=True, blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ClientReportAccess',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('access', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ClientsReporting',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('client_id', models.IntegerField(serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=1000, null=True, blank=True)),
                ('parent_id', models.IntegerField(null=True, blank=True)),
                ('account_type', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='EqdReporting',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('quality_defect', models.CharField(max_length=10, null=True, blank=True)),
                ('title', models.CharField(max_length=300, null=True, verbose_name='title', blank=True)),
                ('client_id', models.IntegerField(null=True, blank=True)),
                ('project_id', models.IntegerField(null=True, blank=True)),
                ('task_id', models.IntegerField(null=True, blank=True)),
                ('project_manager_id', models.IntegerField(null=True, blank=True)),
                ('due_date', models.DateTimeField(null=True, verbose_name='Due Date', blank=True)),
                ('due_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('due_modified', models.DateTimeField(null=True, verbose_name='Date Modified', blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ProjectsReporting',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('project_id', models.IntegerField(serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=1000, null=True, blank=True)),
                ('price', models.DecimalField(default=0.0, null=True, max_digits=15, decimal_places=2, blank=True)),
                ('payment_method', models.CharField(max_length=1000, null=True, blank=True)),
                ('gross_margin', models.DecimalField(default=0.0, null=True, max_digits=15, decimal_places=2, blank=True)),
                ('on_time_delivery', models.CharField(max_length=10, null=True, blank=True)),
                ('project_status', models.CharField(max_length=50, null=True, blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('source_locale', models.CharField(max_length=1000, null=True, blank=True)),
                ('client_po', models.CharField(max_length=1000, null=True, blank=True)),
                ('job_number', models.CharField(max_length=1000, null=True, blank=True)),
                ('account_executive', models.CharField(max_length=1000, null=True, blank=True)),
                ('project_manager_id', models.IntegerField(null=True, blank=True)),
                ('project_manager', models.CharField(max_length=1000, null=True, blank=True)),
                ('estimator_id', models.IntegerField(null=True, blank=True)),
                ('estimator', models.CharField(max_length=1000, null=True, blank=True)),
                ('industry', models.CharField(max_length=1000, null=True, blank=True)),
                ('start_date', models.DateTimeField(null=True, blank=True)),
                ('due_date', models.DateTimeField(null=True, blank=True)),
                ('completed', models.DateTimeField(null=True, blank=True)),
                ('delivered_date', models.DateTimeField(null=True, blank=True)),
                ('quoted', models.DateTimeField(null=True, blank=True)),
                ('priority', models.CharField(max_length=1000, null=True, blank=True)),
                ('estimate_type', models.CharField(max_length=1000, null=True, blank=True)),
                ('instructions', models.TextField(null=True, verbose_name='Client Instructions', blank=True)),
                ('instructions_via', models.TextField(null=True, verbose_name='VIA Instructions', blank=True)),
                ('instructions_vendor', models.TextField(null=True, verbose_name='Supplier Instructions', blank=True)),
                ('project_reference_name', models.CharField(max_length=1000, null=True, blank=True)),
                ('client_poc', models.ForeignKey(blank=True, to='dwh_reports.ClientManager', null=True)),
                ('customer', models.ForeignKey(to='dwh_reports.ClientsReporting')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='RefreshTracking',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('last_refreshed_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TaskRating',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('task_id', models.IntegerField(null=True, blank=True)),
                ('project_id', models.IntegerField(null=True, blank=True)),
                ('job_number', models.CharField(max_length=100, null=True, blank=True)),
                ('task_name', models.TextField(null=True, blank=True)),
                ('assignee_object_id', models.IntegerField(null=True, blank=True)),
                ('assignee_name', models.CharField(max_length=500, null=True, blank=True)),
                ('rating', models.IntegerField(default=0, null=True, blank=True)),
                ('service_id', models.IntegerField(null=True, blank=True)),
                ('service_type', models.CharField(max_length=100, null=True, blank=True)),
                ('notes', models.TextField(null=True, verbose_name='Notes', blank=True)),
                ('via_notes', models.TextField(null=True, verbose_name='Via Notes', blank=True)),
                ('vendor_notes', models.TextField(null=True, verbose_name='Vendor Notes', blank=True)),
                ('started', models.DateTimeField(null=True, blank=True)),
                ('completed', models.DateTimeField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TasksReporting',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('task_id', models.IntegerField(null=True, blank=True)),
                ('status', models.CharField(max_length=50, null=True, blank=True)),
                ('assignee_object_id', models.PositiveIntegerField(null=True, blank=True)),
                ('memory_bank_discount', models.DecimalField(default=0.0, null=True, max_digits=15, decimal_places=2, blank=True)),
                ('gross_margin', models.DecimalField(default=0.0, null=True, max_digits=15, decimal_places=2, blank=True)),
                ('price', models.DecimalField(default=0.0, null=True, max_digits=15, decimal_places=2, blank=True)),
                ('service_id', models.IntegerField(null=True, blank=True)),
                ('service_code', models.CharField(max_length=50, null=True, blank=True)),
                ('service_type', models.CharField(max_length=50, null=True, blank=True)),
                ('target_id', models.IntegerField(null=True, blank=True)),
                ('target', models.CharField(max_length=1000, null=True, blank=True)),
                ('source_file', models.CharField(max_length=1000, null=True, blank=True)),
                ('word_count', models.IntegerField(null=True, blank=True)),
                ('due', models.DateTimeField(null=True, blank=True)),
                ('started', models.DateTimeField(null=True, blank=True)),
                ('completed', models.DateTimeField(null=True, blank=True)),
                ('accepted', models.DateTimeField(null=True, blank=True)),
                ('project', models.ForeignKey(to='dwh_reports.ProjectsReporting')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VendorsReporting',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('client_id', models.IntegerField(serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=1000, null=True, blank=True)),
                ('parent_id', models.IntegerField(null=True, blank=True)),
                ('account_type', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VendorUserReporting',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('department', models.CharField(max_length=255, null=True, blank=True)),
                ('user_type', models.CharField(max_length=255, null=True, blank=True)),
                ('first_name', models.CharField(max_length=1000, null=True, blank=True)),
                ('last_name', models.CharField(max_length=1000, null=True, blank=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('reports_to_id', models.IntegerField(null=True, blank=True)),
                ('account', models.ForeignKey(blank=True, to='dwh_reports.VendorsReporting', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ViaReporting',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('client_id', models.IntegerField(serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=1000, null=True, blank=True)),
                ('parent_id', models.IntegerField(null=True, blank=True)),
                ('account_type', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ViaUserReporting',
            fields=[
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.IntegerField(serialize=False, primary_key=True)),
                ('department', models.CharField(max_length=255, null=True, blank=True)),
                ('user_type', models.CharField(max_length=255, null=True, blank=True)),
                ('first_name', models.CharField(max_length=1000, null=True, blank=True)),
                ('last_name', models.CharField(max_length=1000, null=True, blank=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('reports_to_id', models.IntegerField(null=True, blank=True)),
                ('account', models.ForeignKey(blank=True, to='dwh_reports.ViaReporting', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='clientreportaccess',
            name='client',
            field=models.ForeignKey(to='dwh_reports.ClientsReporting'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='clientreportaccess',
            name='client_report',
            field=models.ForeignKey(to='dwh_reports.ClientReport'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='clientmanager',
            name='account',
            field=models.ForeignKey(blank=True, to='dwh_reports.ClientsReporting', null=True),
            preserve_default=True,
        ),
    ]
