# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-27 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dwh_reports', '0003_auto_20170707_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksreporting',
            name='memory_bank_discount',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=15, null=True),
        ),
    ]
