# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-08 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization_kits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileasset',
            name='asset_type',
            field=models.CharField(choices=[(b'source', b'Source'), (b'reference', b'Reference item'), (b'placeholder', b'Placeholder')], db_index=True, default=b'placeholder', max_length=20),
        ),
        migrations.AlterField(
            model_name='fileasset',
            name='status',
            field=models.CharField(choices=[(b'new', b'New'), (b'queued', b'Queued'), (b'analysis_complete', b'Analysis Complete'), (b'analysis_error', b'Analysis Error')], db_index=True, default=b'new', max_length=20),
        ),
    ]
