# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-27 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization_kits', '0002_auto_20170707_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileasset',
            name='available_on_supplier',
            field=models.NullBooleanField(default=False),
        ),
    ]
