# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import tasks.models
import shared.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        ('localization_kits', '0001_initial'),
        ('projects', '0001_initial'),
        ('contenttypes', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(default=b'created', max_length=40, choices=[(b'created', b'Created'), (b'active', b'Active'), (b'completed', b'Completed'), (b'canceled', b'Canceled')])),
                ('billable', models.BooleanField(default=False)),
                ('assignee_object_id', models.PositiveIntegerField(null=True, blank=True)),
                ('standard_days', models.DecimalField(default=0, max_digits=4, decimal_places=2)),
                ('express_days', models.DecimalField(default=0, max_digits=4, decimal_places=2)),
                ('accepted_timestamp', models.DateTimeField(null=True, blank=True)),
                ('scheduled_start_timestamp', models.DateTimeField(null=True, blank=True)),
                ('due', models.DateTimeField(null=True, blank=True)),
                ('started_timestamp', models.DateTimeField(null=True, blank=True)),
                ('completed_timestamp', models.DateTimeField(null=True, blank=True)),
                ('notes', models.TextField(null=True, blank=True)),
                ('rating', models.IntegerField(default=0, null=True, blank=True)),
                ('via_notes', models.TextField(null=True, verbose_name='Via Notes', blank=True)),
                ('vendor_notes', models.TextField(null=True, verbose_name='Vendor Notes', blank=True)),
                ('vendor_feedback', models.TextField(null=True, verbose_name='Vendor feedback', blank=True)),
                ('current_user', models.IntegerField(null=True, blank=True)),
                ('jams_taskid', models.PositiveIntegerField(null=True, verbose_name='JAMS TaskID', blank=True)),
                ('create_po_needed', models.BooleanField(default=True)),
                ('po_created_date', models.DateTimeField(null=True, blank=True)),
                ('reference_file', models.FileField(max_length=500, null=True, upload_to=tasks.models.wrapper, blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='NonTranslationTask',
            fields=[
                ('task_ptr', models.OneToOneField(parent_link=True, auto_created=True, primary_key=True, serialize=False, to='tasks.Task')),
                ('quantity', models.DecimalField(null=True, max_digits=19, decimal_places=2, blank=True)),
                ('unit_cost', shared.fields.CurrencyField(null=True, max_digits=15, decimal_places=4, blank=True)),
                ('unit_price', shared.fields.CurrencyField(null=True, max_digits=15, decimal_places=4, blank=True)),
                ('price_is_percentage', models.BooleanField(default=False)),
                ('vendor_minimum', shared.fields.CurrencyField(null=True, max_digits=15, decimal_places=4, blank=True)),
                ('actual_hours', models.DecimalField(null=True, max_digits=19, decimal_places=2, blank=True)),
                ('formula', models.ForeignKey(related_name=b'+', blank=True, to='services.PricingFormula', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('tasks.task',),
        ),
        migrations.CreateModel(
            name='TaskLocaleTranslationKit',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('input_file', models.FileField(max_length=500, null=True, upload_to=tasks.models.get_task_input_asset_path, blank=True)),
                ('output_file', models.FileField(max_length=500, null=True, upload_to=tasks.models.get_task_output_asset_path, blank=True)),
                ('support_file', models.FileField(max_length=500, null=True, upload_to=tasks.models.get_task_output_asset_path, blank=True)),
                ('tm_update_file', models.FileField(max_length=500, null=True, upload_to=tasks.models.get_task_output_asset_path, blank=True)),
                ('tm_file_updated_at', models.DateTimeField(null=True, blank=True)),
                ('current_user', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TaskLocalizedAsset',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, null=True, blank=True)),
                ('input_file', models.FileField(max_length=500, null=True, upload_to=tasks.models.get_task_input_asset_path, blank=True)),
                ('output_file', models.FileField(max_length=500, null=True, upload_to=tasks.models.get_task_output_asset_path, blank=True)),
                ('support_file', models.FileField(max_length=500, null=True, upload_to=tasks.models.get_task_support_asset_path, blank=True)),
                ('downloaded', models.DateTimeField(null=True, blank=True)),
                ('post_delivery_file', models.FileField(max_length=500, null=True, upload_to=tasks.models.get_task_post_delivery_asset_path, blank=True)),
                ('post_delivery_notes', models.TextField(null=True, verbose_name='Post-Delivery Comments', blank=True)),
                ('current_user', models.IntegerField(null=True, blank=True)),
                ('via_approved', models.BooleanField(default=False)),
                ('source_asset', models.ForeignKey(blank=True, to='localization_kits.FileAsset', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TranslationTask',
            fields=[
                ('task_ptr', models.OneToOneField(parent_link=True, auto_created=True, primary_key=True, serialize=False, to='tasks.Task')),
            ],
            options={
                'abstract': False,
            },
            bases=('tasks.task',),
        ),
        migrations.CreateModel(
            name='TranslationTaskAnalysis',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('guaranteed', models.IntegerField(default=0, verbose_name='Prfect')),
                ('exact', models.IntegerField(default=0, verbose_name='Exact')),
                ('duplicate', models.IntegerField(default=0, verbose_name='Reps')),
                ('fuzzy9599', models.IntegerField(default=0, verbose_name='95-99')),
                ('fuzzy8594', models.IntegerField(default=0, verbose_name='85-94')),
                ('fuzzy7584', models.IntegerField(default=0, verbose_name='75-84')),
                ('fuzzy5074', models.IntegerField(default=0, verbose_name='50-74')),
                ('no_match', models.IntegerField(default=0, verbose_name='NoMch')),
                ('source_of_analysis', models.IntegerField()),
                ('source', models.ForeignKey(related_name=b'+', to='services.Locale', null=True)),
                ('target', models.ForeignKey(related_name=b'+', to='services.Locale', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TranslationTaskClientPrice',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('guaranteed', shared.fields.CurrencyField(default=0.0, verbose_name='Prfect', max_digits=15, decimal_places=4)),
                ('exact', shared.fields.CurrencyField(default=0.5, verbose_name='Exact', max_digits=15, decimal_places=4)),
                ('duplicate', shared.fields.CurrencyField(default=0.5, verbose_name='Reps', max_digits=15, decimal_places=4)),
                ('fuzzy9599', shared.fields.CurrencyField(default=1.0, verbose_name='95-99', max_digits=15, decimal_places=4)),
                ('fuzzy8594', shared.fields.CurrencyField(default=1.0, verbose_name='85-94', max_digits=15, decimal_places=4)),
                ('fuzzy7584', shared.fields.CurrencyField(default=1.0, verbose_name='75-84', max_digits=15, decimal_places=4)),
                ('fuzzy5074', shared.fields.CurrencyField(default=1.0, verbose_name='50-74', max_digits=15, decimal_places=4)),
                ('no_match', shared.fields.CurrencyField(default=1.0, verbose_name='NoMch', max_digits=15, decimal_places=4)),
                ('source_of_client_prices', models.IntegerField()),
                ('expansion_rate', models.FloatField(default=1.0)),
                ('minimum_price', shared.fields.CurrencyField(default=0.0, null=True, max_digits=15, decimal_places=4, blank=True)),
                ('word_rate', shared.fields.CurrencyField(default=0.0, max_digits=15, decimal_places=4)),
                ('basis', models.ForeignKey(related_name=b'+', blank=True, to='services.PricingBasis', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TranslationTaskVendorRates',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('guaranteed', shared.fields.CurrencyField(default=0.0, verbose_name='Prfect', max_digits=15, decimal_places=4)),
                ('exact', shared.fields.CurrencyField(default=0.5, verbose_name='Exact', max_digits=15, decimal_places=4)),
                ('duplicate', shared.fields.CurrencyField(default=0.5, verbose_name='Reps', max_digits=15, decimal_places=4)),
                ('fuzzy9599', shared.fields.CurrencyField(default=1.0, verbose_name='95-99', max_digits=15, decimal_places=4)),
                ('fuzzy8594', shared.fields.CurrencyField(default=1.0, verbose_name='85-94', max_digits=15, decimal_places=4)),
                ('fuzzy7584', shared.fields.CurrencyField(default=1.0, verbose_name='75-84', max_digits=15, decimal_places=4)),
                ('fuzzy5074', shared.fields.CurrencyField(default=1.0, verbose_name='50-74', max_digits=15, decimal_places=4)),
                ('no_match', shared.fields.CurrencyField(default=1.0, verbose_name='NoMch', max_digits=15, decimal_places=4)),
                ('source_of_vendor_rates', models.IntegerField()),
                ('minimum', shared.fields.CurrencyField(null=True, max_digits=15, decimal_places=4, blank=True)),
                ('word_rate', shared.fields.CurrencyField(default=0.0, max_digits=15, decimal_places=4)),
                ('basis', models.ForeignKey(related_name=b'+', blank=True, to='services.PricingBasis', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='VendorPurchaseOrder',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('po_number', models.IntegerField(null=True, blank=True)),
                ('status', models.CharField(default=b'open', max_length=40, choices=[(b'new', b'New'), (b'open', b'Open'), (b'closed', b'Closed'), (b'canceled', b'Canceled')])),
                ('notes', models.TextField(null=True, blank=True)),
                ('due', models.DateTimeField(null=True, blank=True)),
                ('paid', models.BooleanField(default=False)),
                ('acct_purchaseorder_txn_id', models.CharField(max_length=50, null=True, blank=True)),
                ('acct_bill_txn_id', models.CharField(max_length=50, null=True, blank=True)),
                ('task', models.OneToOneField(related_name=b'po', to='tasks.Task')),
                ('vendor', models.ForeignKey(to='vendors.Vendor')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='translationtask',
            name='analysis',
            field=models.ForeignKey(to='tasks.TranslationTaskAnalysis', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='translationtask',
            name='client_price',
            field=models.OneToOneField(null=True, to='tasks.TranslationTaskClientPrice'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='translationtask',
            name='vendor_rates',
            field=models.OneToOneField(null=True, to='tasks.TranslationTaskVendorRates'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='tasklocalizedasset',
            name='task',
            field=models.ForeignKey(related_name=b'localized_assets', to='tasks.Task'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='tasklocaletranslationkit',
            name='task',
            field=models.OneToOneField(related_name=b'trans_kit', to='tasks.Task'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='task',
            name='assignee_content_type',
            field=models.ForeignKey(blank=True, to='contenttypes.ContentType', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='task',
            name='predecessor',
            field=models.ForeignKey(related_name=b'children', blank=True, to='tasks.Task', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(to='projects.Project'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='task',
            name='service',
            field=models.ForeignKey(related_name=b'+', blank=True, to='services.Service', null=True),
            preserve_default=True,
        ),
    ]
