# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-01 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import shared.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20160907_1430'),
        ('tasks', '0002_auto_20160907_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('unit_cost', shared.fields.CurrencyField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('unit_price', shared.fields.CurrencyField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('raw_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('mbd', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('net_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('gm', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
