# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-07 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='express_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='task',
            name='standard_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
