# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localization_kits', '0001_initial'),
        ('tasks', '0004_auto_20160913_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssetQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('asset_total_cost', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True)),
                ('asset_raw_price', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True)),
                ('asset_mbd', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True)),
                ('asset_net_price', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True)),
                ('asset_gm', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True)),
                ('asset_is_minimum_price', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='localization_kits.FileAsset')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='taskquote',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='taskquote',
            name='unit_cost',
        ),
        migrations.RemoveField(
            model_name='taskquote',
            name='unit_price',
        ),
    ]
