# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-05 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20160927_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassetquote',
            name='target_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
