# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-13 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_taskassetquote_target_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassetquote',
            name='asset_express_gm',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='taskassetquote',
            name='asset_express_mbd',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='taskassetquote',
            name='asset_express_net_price',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='taskassetquote',
            name='asset_express_raw_price',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='taskassetquote',
            name='asset_total_express_cost',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='taskquote',
            name='express_gm',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='taskquote',
            name='express_mbd',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='taskquote',
            name='express_net_price',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='taskquote',
            name='express_raw_price',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='taskquote',
            name='total_express_cost',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=15, null=True),
        ),
    ]
