# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_merge_20161102_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassetquote',
            name='asset_wordcount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
