# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-14 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20161114_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='overdue_email_last_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='qa_approved',
            field=models.BooleanField(default=False),
        ),
    ]
