# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-15 14:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_task_qa_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='qa_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
