# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_load_intial_data'),
        ('projects', '0002_auto_20160427_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectServicesGlobal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='restricted_locations',
            field=models.ManyToManyField(blank=True, related_name='_project_restricted_locations_+', to='services.Country'),
        ),
        migrations.AlterField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='_project_services_+', to='services.ServiceType'),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_locales',
            field=models.ManyToManyField(blank=True, related_name='_project_target_locales_+', to='services.Locale'),
        ),
        migrations.AddField(
            model_name='projectservicesglobal',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_global', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='projectservicesglobal',
            name='servicetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_globaltype', to='services.ServiceType'),
        ),
        migrations.AddField(
            model_name='project',
            name='services_global',
            field=models.ManyToManyField(blank=True, related_name='service_global', through='projects.ProjectServicesGlobal', to='services.ServiceType'),
        ),
    ]
