# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20160531_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectservicesglobal',
            name='express_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='projectservicesglobal',
            name='standard_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
