# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-08 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20160907_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricequote',
            name='target_express_tat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricequote',
            name='target_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricequote',
            name='target_standard_tat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
