# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-03 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20161003_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricequotedetails',
            name='pricequote',
        ),
        migrations.AddField(
            model_name='pricequotedetails',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
