# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-03 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20161003_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricequotedetails',
            name='project',
        ),
        migrations.AddField(
            model_name='pricequote',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricequote',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricequotedetails',
            name='pricequote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.PriceQuote'),
        ),
    ]
