# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-05 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20161003_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricequote',
            name='express_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='pricequote',
            name='express_gm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='pricequote',
            name='express_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='pricequote',
            name='wordcount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
