# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-13 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20161005_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricequotedetails',
            name='target_express_cost',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='pricequotedetails',
            name='target_express_gross_margin',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='pricequotedetails',
            name='target_express_price',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
    ]
