# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-18 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20161013_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricequote',
            name='express_tat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='pricequote',
            name='standard_tat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
    ]
