# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-26 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20161018_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricequote',
            name='express_gm',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='pricequote',
            name='gm',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=15, null=True),
        ),
    ]
