# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-27 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_load_intial_data'),
        ('projects', '0017_auto_20161026_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricequotedetails',
            name='target_id',
        ),
        migrations.AddField(
            model_name='pricequotedetails',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Locale'),
        ),
    ]
