# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20160907_1430'),
        ('projects', '0018_auto_20161027_1528'),
    ]

    operations = [
    ]
