# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 08:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_load_intial_data'),
        ('projects', '0021_auto_20170315_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_access_given', models.BooleanField(choices=[(True, 'Access given'), (False, 'No Access')], default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='_project_assigned_to_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='_project_services_+', to='services.ServiceType'),
        ),
        migrations.AddField(
            model_name='projectaccess',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_project', to='projects.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='access_request',
            field=models.ManyToManyField(blank=True, null=True, related_name='access_project', through='projects.ProjectAccess', to=settings.AUTH_USER_MODEL),
        ),
    ]
