# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_auto_20160607_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_restricted_job',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_secure_job',
            field=models.NullBooleanField(default=False),
        ),
    ]
