# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 20:18
from __future__ import unicode_literals
from django.db import migrations
from projects.models import Project


def load_data(apps, schema_editor):
    project_set = Project.objects.all()

    for project in project_set:
        print(project)
        try:
            quote = project.quote()
            print(project.price())
        except Exception, error:
            print(error)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20170707_1109'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
