# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-08 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_rebuild_projectquote_price_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='job_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[(b'quoted', 'Estimated'), (b'created', 'In Estimate'), (b'started', 'Active'), (b'completed', 'Delivered'), (b'canceled', 'Canceled'), (b'closed', 'Closed'), (b'hold', 'Hold'), (b'queued', 'Queued')], db_index=True, default=b'queued', max_length=40),
        ),
        migrations.AlterField(
            model_name='projectteamrole',
            name='role',
            field=models.CharField(blank=True, choices=[(b'pm', b'Project Manager'), (b'ae', b'Account Executive'), (b'tsg_eng', b'TSG Engineer'), (b'vle_eng', b'VLE Engineer'), (b'qa_eng', b'QA Engineer'), (b'sjt_member', b'Secure Job Team Member'), (b'psj_team', b'PHI Secure Job Team Member')], db_index=True, max_length=10, null=True),
        ),
    ]
