# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-18 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_auto_20170707_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectJobOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editable_source', models.NullBooleanField(default=False)),
                ('recreation_source', models.NullBooleanField(default=False)),
                ('translation_unformatted', models.NullBooleanField(default=False)),
                ('translation_billingual', models.NullBooleanField(default=False)),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.Project')),
            ],
        ),
    ]
