# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-28 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_projectjoboptions'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='project',
        #     name='supplier_reference',
        # ),
    ]
